### ISSUE TITLE
2 questions :)

### ISSUE THREAD

**Issue by Stan92** [leyleo/leowebdav#3]
First of all, thanks for sharing your code..
My questions are about the LEOWebDAVMoveRequest method...
It seems it's not implemented, right?
And how should be the Rename method?
I m very new to webdav...
Regards.

**Comment by leyleo** [comment]
The LEOWebDAVMoveRequest has been implemented.
as following:

```
LEOWebDAVMoveRequest *moveRequest=[[LEOWebDAVMoveRequest alloc] initWithPath:_currentItem.href];
[moveRequest setDestinationPath:newName];
moveRequest.overwrite=YES;
[moveRequest setDelegate:self];
[_currentClient enqueueRequest:moveRequest];
```
