### ISSUE TITLE
Upload and download progress??

### ISSUE THREAD

**Issue by hatim-haffane** [leyleo/leowebdav#5]
hello , first of all thank you for your code , and i'm just asking how i can get the download and the upload progress of a file ?? 

thanks

**Comment by leyleo** [comment]
There're 3 optional `LEOWebDAVRequestDelegate` protocal methods about process:

``` objective-c
- (void)requestDidBegin:(LEOWebDAVRequest *)request;
- (void)request:(LEOWebDAVRequest *)request didReceivedProgress:(float)percent;
- (void)request:(LEOWebDAVRequest *)request didSendBodyData:(NSUInteger)percent;
```
