### ISSUE TITLE
getting the Parent folder as a childe of his self ???

### ISSUE THREAD

**Issue by hatim-haffane** [leyleo/leowebdav#6]
hello , sometimes when i try to get the childs files of a directory , i get the directory as a child of his self . can you please help me to fix that ?

**Comment by leyleo** [comment]
It seems that method

``` objective-c
-(id)resultForData:(NSData *)data
```

in `LEOWebDAVPropertyRequest` class processed the problem, such as line 63:

``` objective-c
if (![item.displayName hasPrefix:@"."]) {
```

when the item displayname start with ".", I think it's a hidden file, so it not be added to property list array.

**Comment by hatim-haffane** [comment]
yes but the item.displayName is always nil , i don't know why , i try to see what happend on the parser class , but i did not find where you get the displayName ???

**Comment by leyleo** [comment]
from the `LEOWebDAVPropertyRequest` class, when generate the property request, i setup request for all property which is defined in `LEOWebDAVDefines.h` as kWebDAVProperty,  

``` objective-c
kWebDAVProperty = LEOWebDAVPropertyAllProperties
```

that means when i start propery request, i generate request body in `LEOWebDAVPropertyRequest.m` during line76 to line116, with all kinds of properties, include `<D:displayname/>`

**Comment by leyleo** [comment]
U just need to define `kWebDAVProperty` as the `LEOWebDAVProperties` type. 
The `LEOWebDAVProperties` type define is in `LEOWebDAVPropertyRequest.h`
